# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_course_course_creator'),
        ('login_register', '0002_auto_20170119_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='course_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='course.Course'),
            preserve_default=False,
        ),
    ]
