# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 23:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_course_course_creator'),
        ('login_register', '0003_user_course_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='course_id',
        ),
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_users', to='course.Course'),
            preserve_default=False,
        ),
    ]
