# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0002_auto_20170119_1744'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login_register.User'),
            preserve_default=False,
        ),
    ]
