# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 21:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_course_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_creator',
        ),
    ]
